// <auto-generated />
using System;
using EducationalCompanion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducationalCompanion.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuleDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Badges", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.GamificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpGranted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("GamificationEvents", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.LearningResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LearningResources", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmUsed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("LearningResourceId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LearningResourceId");

                    b.ToTable("Recommendations", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.ResourceMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmbeddingVectorJson")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LearningResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningResourceId")
                        .IsUnique();

                    b.ToTable("ResourceMetadata", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.ScheduleSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StudyTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SuggestedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuggestedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudyTaskId");

                    b.ToTable("ScheduleSuggestions", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.StudyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LearningResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningResourceId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("StudyTasks", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserBadges", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InteractionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearningResourceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSpentMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningResourceId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserInteractions", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredContentTypesCsv")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PreferredDifficulty")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredTopicsCsv")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyAvailableMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.GamificationEvent", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("GamificationEvents")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.LearningResource", "LearningResource")
                        .WithMany()
                        .HasForeignKey("LearningResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningResource");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.ResourceMetadata", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.LearningResource", "LearningResource")
                        .WithOne("Metadata")
                        .HasForeignKey("EducationalCompanion.Domain.Entities.ResourceMetadata", "LearningResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningResource");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.ScheduleSuggestion", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.StudyTask", "StudyTask")
                        .WithMany()
                        .HasForeignKey("StudyTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyTask");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.StudyTask", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.LearningResource", "LearningResource")
                        .WithMany()
                        .HasForeignKey("LearningResourceId");

                    b.HasOne("EducationalCompanion.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Tasks")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("LearningResource");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationalCompanion.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("Badge");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserInteraction", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.LearningResource", "LearningResource")
                        .WithMany("Interactions")
                        .HasForeignKey("LearningResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationalCompanion.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Interactions")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("LearningResource");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("EducationalCompanion.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("Preferences")
                        .HasForeignKey("EducationalCompanion.Domain.Entities.UserPreferences", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.LearningResource", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("EducationalCompanion.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("GamificationEvents");

                    b.Navigation("Interactions");

                    b.Navigation("Preferences");

                    b.Navigation("Tasks");

                    b.Navigation("UserBadges");
                });
#pragma warning restore 612, 618
        }
    }
}
